# -------------------- Zookeeper Service --------------------- #

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2181
  - name: follower
    port: 2888
  - name: leader
    port: 3888
  selector:
    app: zookeeper-1

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2181
  - name: follower
    port: 2888
  - name: leader
    port: 3888
  selector:
    app: zookeeper-2

---
    
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2181
  - name: follower
    port: 2888
  - name: leader
    port: 3888
  selector:
    app: zookeeper-3

---    
    
# ------------------- Zookeeper Deployment ------------------- #

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
      - name: zookeeper-1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-1
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper-3
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-2
  template:
    metadata:
      labels:
        app: zookeeper-2
    spec:
      containers:
      - name: zookeeper-2
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-1
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper-3
          
---          

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-3  
  template:
    metadata:
      labels:
        app: zookeeper-3
    spec:
      containers:
      - name: zookeeper-3
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "3"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-1
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper-3
         
