# -------------------- Kafka Service --------------------- #

apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  clusterIP: None
  ports:
  - name: broker
    port: 9092
  selector:
    app: kafka-1

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-2
spec:
  clusterIP: None
  ports:
  - name: broker
    port: 9092
  selector:
    app: kafka-2

---
    
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
spec:
  clusterIP: None
  ports:
  - name: broker
    port: 9092
  selector:
    app: kafka-3
 
---
 
# ------------------- Kafka Deployment ------------------- #

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
      - name: kafka-1
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: hellotopic:3:3
---        

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
      - name: kafka-2
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_CREATE_TOPICS
          value: hellotopic:3:3          
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-3
  template:
    metadata:
      labels:
        app: kafka-3
    spec:
      containers:
      - name: kafka-3
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "kafka-3"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          - name: KAFKA_BROKER_ID
            value: "3"
          - name: KAFKA_CREATE_TOPICS
            value: hellotopic:3:3